openapi: 3.0.1
info:
  title: transport.proto
  version: version not set
servers:
- url: ''
paths:
  /api/v2private/flows/orgs/{orgID}/flows:
    get:
      tags:
      - FlowAPI
      operationId: FlowAPI_ListFlows
      parameters:
      - name: orgID
        in: path
        required: true
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: integer
          format: int64
      - name: pageToken
        in: query
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transportFlowList'
        default:
          description: An unexpected error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    post:
      tags:
      - FlowAPI
      operationId: FlowAPI_CreateFlow
      parameters:
      - name: orgID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transportFlowCreateRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transportFlow'
        default:
          description: An unexpected error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-codegen-request-body-name: body
  /api/v2private/flows/orgs/{orgID}/flows/{id}:
    get:
      tags:
      - FlowAPI
      operationId: FlowAPI_GetFlow
      parameters:
      - name: orgID
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transportFlow'
        default:
          description: An unexpected error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    delete:
      tags:
      - FlowAPI
      operationId: FlowAPI_DeleteFlow
      parameters:
      - name: orgID
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
    patch:
      tags:
      - FlowAPI
      operationId: FlowAPI_UpdateFlow
      parameters:
      - name: orgID
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transportFlowUpdateRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transportFlow'
        default:
          description: An unexpected error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      x-codegen-request-body-name: body
components:
  schemas:
    protobufAny:
      type: object
      properties:
        type_url:
          type: string
        value:
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
          format: byte
    protobufNullValue:
      type: string
      description: |-
        `NullValue` is a singleton enumeration to represent the null value for the
        `Value` type union.

         The JSON representation for `NullValue` is JSON `null`.

         - NULL_VALUE: Null value.
      default: NULL_VALUE
      enum:
      - NULL_VALUE
    runtimeError:
      type: object
      properties:
        error:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    transportFlow:
      type: object
      properties:
        orgID:
          type: string
        id:
          type: string
        name:
          type: string
        spec:
          type: object
          properties: {}
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    transportFlowCreateRequest:
      type: object
      properties:
        orgID:
          type: string
        name:
          type: string
        spec:
          type: object
          properties: {}
    transportFlowList:
      type: object
      properties:
        flows:
          type: array
          items:
            $ref: '#/components/schemas/transportFlow'
        nextPageToken:
          type: string
    transportFlowUpdateRequest:
      type: object
      properties:
        orgID:
          type: string
        id:
          type: string
        name:
          $ref: '#/components/schemas/transportString'
        spec:
          type: object
          properties: {}
    transportString:
      type: object
      properties:
        value:
          type: string
