FROM nginx:stable-alpine

ARG ASSETS

# We hard copy these assets in so that the image can
# be transported without a volume claim + cloud specific
# storage mechanism. It does make images a little bigger
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ${ASSETS} /usr/share/nginx/html/

EXPOSE 9999
