import {PROJECT_NAME_PLURAL} from 'src/flows'

export const buildDeepLinkingMap = (orgId: string) => ({
  '/me/org-settings': `/orgs/${orgId}/org-settings`,
  '/me/alerts': `/orgs/${orgId}/alerting`,
  '/me/billing': `/orgs/${orgId}/billing`,
  '/me/buckets': `/orgs/${orgId}/load-data/buckets`,
  '/me/csharpclient': `/orgs/${orgId}/load-data/client-libraries/csharp`,
  '/me/dashboards': `/orgs/${orgId}/dashboards-list`,
  '/me/data-explorer': `/orgs/${orgId}/data-explorer`,
  '/me/goclient': `/orgs/${orgId}/load-data/client-libraries/go`,
  '/me/home': `/orgs/${orgId}`,
  '/me/javaclient': `/orgs/${orgId}/load-data/client-libraries/java`,
  '/me/labels': `/orgs/${orgId}/settings/labels`,
  '/me/load-data': `/orgs/${orgId}/load-data/sources`,
  '/me/nodejsclient': `/orgs/${orgId}/load-data/client-libraries/javascript-node`,
  [`/me/${PROJECT_NAME_PLURAL.toLowerCase()}`]: `/orgs/${orgId}/${PROJECT_NAME_PLURAL.toLowerCase()}`,
  '/me/notebooks': `/orgs/${orgId}/${PROJECT_NAME_PLURAL.toLowerCase()}`,
  '/me/profile': `/orgs/${orgId}/user/profile`,
  '/me/pythonclient': `/orgs/${orgId}/load-data/client-libraries/python`,
  '/me/secrets': `/orgs/${orgId}/settings/secrets`,
  '/me/setup-arduino': `/orgs/${orgId}/new-user-setup/arduino`,
  '/me/setup-cli': `/orgs/${orgId}/new-user-setup/cli`,
  '/me/setup-golang': `/orgs/${orgId}/new-user-setup/golang`,
  '/me/setup-nodejs': `/orgs/${orgId}/new-user-setup/nodejs`,
  '/me/setup-python': `/orgs/${orgId}/new-user-setup/python`,
  '/me/tasks': `/orgs/${orgId}/tasks`,
  '/me/telegraf-mqtt': `/orgs/${orgId}/load-data/telegraf-plugins/mqtt_consumer`,
  '/me/telegrafs': `/orgs/${orgId}/load-data/telegrafs`,
  '/me/templates': `/orgs/${orgId}/settings/templates`,
  '/me/tokens': `/orgs/${orgId}/load-data/tokens`,
  '/me/usage': `/orgs/${orgId}/usage`,
  '/me/members': `/orgs/${orgId}/members`,
  '/me/variables': `/orgs/${orgId}/settings/variables`,
})
