export const testOrgs = [
  {
    id: '9296169091c64567',
    name: 'Royal Matrix',
    isDefault: true,
    isActive: true,
    provider: 'AWS',
    regionCode: 'us-east-1',
    regionName: 'US East (N. Virginia)',
  },
  {
    id: 'a71ced2b8238902b',
    name: 'Expensive Identification',
    isDefault: false,
    isActive: false,
    provider: 'AWS',
    regionCode: 'eu-central-1',
    regionName: 'EU Frankfurt',
  },
  {
    id: 'ac3d3c04b8f1a545',
    name: 'Lucky Corner',
    isDefault: false,
    isActive: false,
    provider: 'AWS',
    regionCode: 'us-east-1-2',
    regionName: 'US East (N. Virginia) 2',
  },
  {
    id: 'fc734484afa0fcaa',
    name: 'Grammatical Pasture',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'us-west-2-2',
    regionName: 'US West (Oregon)',
  },
  {
    id: '62cba0af4760ce02',
    name: 'Pleasant Circumstance',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'westeurope',
    regionName: 'Amsterdam',
  },
  {
    id: '58fafbb4f68e05e5',
    name: 'Worthy Lawn',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'eastus',
    regionName: 'Virginia',
  },
  {
    id: '3f3fd71611a4a0fe',
    name: 'Inadequate Yield',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'eu-west1',
    regionName: 'Belgium',
  },
  {
    id: '1232a0085d2af2dd',
    name: 'Jealous Nest',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-central1',
    regionName: 'Iowa',
  },
  {
    id: 'e337e5c5ee6439a2',
    name: 'Lesser Flock',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-central1-2',
    regionName: 'Iowa',
  },
  {
    id: '3b3ca09032853015',
    name: 'Chief Staircase',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-west1',
    regionName: 'Oregon',
  },
  {
    id: '9296169091c63567',
    name: 'Bourgeois Cluster',
    isDefault: true,
    isActive: true,
    provider: 'AWS',
    regionCode: 'us-east-1',
    regionName: 'US East (N. Virginia)',
  },
  {
    id: 'a71ced2b8238802b',
    name: 'Mathematical Compromise',
    isDefault: false,
    isActive: false,
    provider: 'AWS',
    regionCode: 'eu-central-1',
    regionName: 'EU Frankfurt',
  },
  {
    id: 'ac3d3c04b8f2a545',
    name: 'National Island',
    isDefault: false,
    isActive: false,
    provider: 'AWS',
    regionCode: 'us-east-1-2',
    regionName: 'US East (N. Virginia) 2',
  },
  {
    id: 'fc734484afe0fcac',
    name: 'Lively Reception',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'us-west-2-2',
    regionName: 'US West (Oregon)',
  },
  {
    id: '62cba0af4460ce02',
    name: 'Incredible Draft',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'westeurope',
    regionName: 'Amsterdam',
  },
  {
    id: 'fc734484afe0f0fe',
    name: 'Absurd Flavor',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'eastus',
    regionName: 'Virginia',
  },
  {
    id: '3f3fd71631a4a0fe',
    name: 'Mean Rehabilitation',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'eu-west1',
    regionName: 'Belgium',
  },
  {
    id: '1232a0081d2af2dd',
    name: 'False Mainland',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-central1',
    regionName: 'Iowa',
  },
  {
    id: 'e337e5d5ee6439a2',
    name: 'Archaelogical Customer',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-central1-2',
    regionName: 'Iowa',
  },
  {
    id: '3b3ca08032853015',
    name: 'Glad Flower',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-west1',
    regionName: 'Oregon',
  },
  {
    id: '9296169091c54567',
    name: 'Walking Ancestor',
    isDefault: true,
    isActive: true,
    provider: 'AWS',
    regionCode: 'us-east-1',
    regionName: 'US East (N. Virginia)',
  },
  {
    id: 'b71ced2b8238902b',
    name: 'Marginal Equation',
    isDefault: false,
    isActive: false,
    provider: 'AWS',
    regionCode: 'eu-central-1',
    regionName: 'EU Frankfurt',
  },
  {
    id: 'ac3d2c04b8f1a545',
    name: 'Legitimate Coin',
    isDefault: false,
    isActive: false,
    provider: 'AWS',
    regionCode: 'us-east-1-2',
    regionName: 'US East (N. Virginia) 2',
  },
  {
    id: 'fc734484afa0fcac',
    name: 'Subsequent Assistant',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'us-west-2-2',
    regionName: 'US West (Oregon)',
  },
  {
    id: '62cba0af4860ce02',
    name: 'Proportional Politics',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'westeurope',
    regionName: 'Amsterdam',
  },
  {
    id: '58eafbb4f68e05e5',
    name: 'Elegant Rope',
    isDefault: false,
    isActive: false,
    provider: 'Azure',
    regionCode: 'eastus',
    regionName: 'Virginia',
  },
  {
    id: '3f3fd71611a4a1fe',
    name: 'Advisory Eyebrow',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'eu-west1',
    regionName: 'Belgium',
  },
  {
    id: '1232a0085d2af2cd',
    name: 'Shallow Motion',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-central1',
    regionName: 'Iowa',
  },
  {
    id: 'e337e6c5ee6439a2',
    name: 'Doubtful Act',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-central1-2',
    regionName: 'Iowa',
  },
  {
    id: '3b3ca09032853014',
    name: 'Financial Subsidiary',
    isDefault: false,
    isActive: false,
    provider: 'GCP',
    regionCode: 'us-west1',
    regionName: 'Oregon',
  },
]
