import {parse} from './parser'

test('parser', () => {
  import('./microsoft_parser')
  // parse()
  })

// grammar
// DATE_TIME = DATE TIME (PERIOD?) (TIMEZONE?)
// DATE_TIME = MONTH_NAME DAY COMMA YEAR TIME (PERIOD?)
// DATE_TIME = DAY_NAME COMMA MONTH_NAME DAY COMMA YEAR TIME (PERIOD?)

// DATE = YEAR HYPHEN MONTH HYPHEN DAY
// DATE = DAY FORWARD_SLASH MONTH FORWARD_SLASH YEAR
// DATE = MONTH FORWARD_SLASH DAY FORWARD_SLASH YEAR
// DATE = YEAR FORWARD_SLASH MONTH FORWARD_SLASH DAY

// TIME = HOUR COLON MINUTE COLON SECONDS (DOT?) (MILLISECONDS?)

// PERIOD = "AM" | "PM"

// TIMEZONE = WORD

//
